import type { AnalysisOutputs, Incident } from './types';

export type FullAnalysisInput = {
  eventDate: string;
  rawInput: string;
  optionalContext: string;
  privateNotes?: string;
  outputs: AnalysisOutputs;
  title?: string;
};

function section(title: string, body: string) {
  return [`## ${title}`, '', body.trim() || '(empty)', '', '—'.repeat(40), ''];
}

function listSection(title: string, items: string[]) {
  const body =
    items.length > 0 ? items.map((i) => `• ${i}`).join('\n') : '(none)';
  return section(title, body);
}

export function buildFullAnalysisExport(data: FullAnalysisInput): string {
  const { eventDate, rawInput, optionalContext, privateNotes, outputs, title } =
    data;
  const heading = title?.trim() || 'Communication analysis';

  const lines: string[] = [
    'CONFLICT BUDDY — FULL ANALYSIS EXPORT',
    heading,
    `Event date: ${eventDate}`,
    `Exported: ${new Date().toISOString().slice(0, 10)}`,
    '',
    'Writing and documentation aid only — not legal advice or therapy.',
    '',
    '='.repeat(48),
    '',
    ...section('Your input (what happened)', rawInput),
  ];

  if (optionalContext?.trim()) {
    lines.push(...section('Background context (optional)', optionalContext));
  }

  if (privateNotes?.trim()) {
    lines.push(
      ...section('Private notes (for your records only)', privateNotes)
    );
  }

  lines.push(
    ...section('De-escalated response', outputs.deEscalatedResponse),
    ...section('Boundary response', outputs.boundaryResponse),
    ...section('Court-safe version', outputs.courtSafeVersion),
    ...section('Log entry', outputs.logEntry),
    ...listSection('Key facts', outputs.keyFacts),
    ...listSection('Suggested tags', outputs.suggestedTags),
    ...listSection('Risk notes', outputs.riskNotes),
    ...listSection('Omitted or softened', outputs.omittedOrSoftened),
    'End of export.'
  );

  return lines.join('\n');
}

export function buildChronologyText(incidents: Incident[]): string {
  if (incidents.length === 0) {
    return 'No incidents selected.';
  }

  const sorted = [...incidents].sort(
    (a, b) => new Date(a.eventDate).getTime() - new Date(b.eventDate).getTime()
  );

  const dates = sorted.map((i) => i.eventDate).filter(Boolean);
  const rangeStart = dates[0] ?? '';
  const rangeEnd = dates[dates.length - 1] ?? '';

  const lines: string[] = [
    'COMMUNICATION CHRONOLOGY',
    'Conflict Buddy — factual log export',
    '',
    `Date range: ${rangeStart}${rangeEnd && rangeEnd !== rangeStart ? ` – ${rangeEnd}` : ''}`,
    `Entries: ${sorted.length}`,
    '',
    '—'.repeat(48),
    '',
  ];

  let lastDate = '';
  for (const incident of sorted) {
    if (incident.eventDate !== lastDate) {
      if (lastDate) lines.push('');
      lines.push(`## ${incident.eventDate}`);
      lines.push('');
      lastDate = incident.eventDate;
    }

    lines.push(`### ${incident.title}`);
    if (incident.tags.length > 0) {
      lines.push(`Tags: ${incident.tags.join(', ')}`);
    }
    lines.push('');
    lines.push(incident.outputs.logEntry.trim() || '(No log entry recorded.)');
    lines.push('');
    lines.push('—'.repeat(32));
    lines.push('');
  }

  lines.push(
    '—',
    'Generated by Conflict Buddy. Writing and documentation aid only — not legal advice or therapy.'
  );

  return lines.join('\n');
}

export function buildChronologyHtml(incidents: Incident[]): string {
  const text = buildChronologyText(incidents);
  const escaped = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Communication Chronology</title>
  <style>
    body { font-family: Georgia, serif; max-width: 720px; margin: 2rem auto; line-height: 1.5; color: #1a2b3c; }
    pre { white-space: pre-wrap; font-family: inherit; font-size: 14px; }
  </style>
</head>
<body>
  <pre>${escaped}</pre>
</body>
</html>`;
}
